sudo: required

services:
  - docker

dist: trusty

language: go

matrix:
  include:
    - go: 1.6

install:
  - sudo apt-get install libseccomp-dev 
  - mkdir -p $HOME/gopath/src/k8s.io
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/k8s.io/kubernetes
  - cd $HOME/gopath/src/k8s.io/kubernetes
  - export LOG_LEVEL=4
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/k8s.io/kubernetes
  - export PATH=$GOPATH/bin:./third_party/etcd:$PATH
  - export KUBE_GOVERALLS_BIN=$GOPATH/bin/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/tools/godep
  - go get github.com/mattn/goveralls
  - go get github.com/jstemmer/go-junit-report
  - ./hack/install-protoc.sh
  - ./hack/install-etcd.sh
  - travis_wait 30 ./hack/build-go.sh
  - travis_wait 30 godep go install ./...
  - ./hack/verify-gofmt.sh
  - ./hack/verify-boilerplate.sh
  - ./hack/verify-description.sh
  - ./hack/verify-flags-underscore.py
  - ./hack/verify-codecgen.sh
  - ./hack/verify-codegen.sh 
  - ./hack/verify-generated-docs.sh
  - ./hack/verify-generated-swagger-docs.sh
  - ./hack/verify-swagger-spec.sh

script:
  - cd $HOME/gopath/src/k8s.io/kubernetes
  # Disable test-go.sh because of travis timeout (50 mins)
  # - ./hack/test-go.sh
  - sudo PATH=$GOPATH/bin:./third_party/etcd:$PATH ./hack/test-cmd.sh

notifications:
  slack:
    secure: fUsnnU0AlBqHxea4h1asZerpYVwLGpqTlZ4APD2Q8EqG3WChN/O74CR/lyTDceSvnjmEoOcxLc/ETXvZ3FrjEAc9ZUxdPcfl7InKYSU9dWzsRCwZLwCnmaphlXFCi6VaPkUvS0J3JPyUS3mF/rNa3l63CTEzp9ni0WFETztZXr16kbTbZJ9FqZ4XYdtSh883ZPc0DPgfSH/iO4nsHGBDFyemW60rccTtNLS0Kac7UyGf16nOo63KWnvtvrsgN+hIYuu5R1xUu+aMRyO3FJ/4jzfhcplKuN1+SJxvvVYpmywuML3FulDhHIuqjOXMYgqCJtug33XNvgXNoInMfAQT4Be3WOtjVg50sx7RCTxwe3uleWd35SAzZcAFl12JGQmnA0IkDoWu6ti8Gc0f1RpqB02Nj4nscaNHYpZOPM32JAji4iMviy00hXhIZkLeTjnQny2FVLPCrTPDGhxJhFIRVF2PtbtcmjrkiUdO2p7K5Cpgl6Ix66557A+8UpSrdv8LollNTG5+/mhy8hLuHf+PrJcsKf09qLAYFhiD2VF+gZxUX94wC2QJQw4iLmMMdHy94GhJprIrCLo5z2u4M8IjIpvjhSsXtJcmmQXsmAEQAtawIVID57A7Z5VCQV3QtxIpdr6dGiuNfXtSxXQ16AQHYpvLn092MiokAag1aktSZTw=
